version: '3.7'
services:
  dynamodb-local:
  image: amazon/dynamodb-local
  container_name: dynamodb-local
  ports:
    - "8000:8000"
networks:
  - ddb-local

networks:
  ddb-local:
    external: true