version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - ${EXMENT_DOCKER_HTTP_PORTS-8080}:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - www-data:/var/www
    env_file: .env
#    networks:
#      - exment-network
    depends_on:
      - php
    environment:
      - VIRTUAL_HOST=${EXMENT_DOCKER_FRONT_DOMAIN-localhost}

  php:
    build: ./php
    volumes:
      - www-data:/var/www
    env_file: .env
    depends_on:
      - db
#    networks:
#      - exment-network

  db:
    image: mysql:5.7
    ports:
      - ${EXMENT_DOCKER_MYSQL_PORT-13306}:3306
    volumes:
      - mysql-data:/var/lib/mysql
    env_file: .env
#    networks:
#      - exment-network
    environment:
      MYSQL_DATABASE: ${EXMENT_DOCKER_MYSQL_DATABASE-exment_database}
      MYSQL_ROOT_PASSWORD: ${EXMENT_DOCKER_MYSQL_ROOT_PASSWORD-secret}
      MYSQL_USER: ${EXMENT_DOCKER_MYSQL_USER-exment_user}
      MYSQL_PASSWORD: ${EXMENT_DOCKER_MYSQL_PASSWORD-secret}

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    env_file: .env
    ports:
      - ${EXMENT_DOCKER_PHPMYADMIN_PORT-8888}:80
#    networks:
#      - exment-network
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      - db

# volumes を定義する
volumes:
  # volume の名前を指定
  # Exmentのインストールパス
  www-data:
    # Compose の外ですでに作成済みの volume を指定する場合は ture を設定する。
    # そうすると、 docker-compose up 時に Compose は volume を作成しようとしません。
    # かつ、指定した volume が存在しないとエラーを raise します。
    # external: true
  # mysql dbのインストールパス
  mysql-data:
  # external: true

# networks:
#    exment-network: