# phpMyAdmin : http://localhost:3000/
version: '3.7'
services:
  mysql:
# https://hub.docker.com/_/mysql/tags
    image: mysql:latest
#    image: mysql:8.0.31
#    container_name: mysql
    ports:
      - 3306:3306
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/db/sql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_database
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
#    hostname: mysql
#    restart: always
  phpmyadmin:
# https://hub.docker.com/r/phpmyadmin/phpmyadmin/tags
#    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    environment:
    - PMA_ARBITRARY=1
    - PMA_HOSTS=mysql     # mysqlのサービス名
    - PMA_USER=docker     # phpmyadminにログインするユーザを設定
    - PMA_PASSWORD=docker # phpmyadminにログインするユーザのパスワードを設定
    volumes:
      - ./docker/phpmyadmin/sessions:/sessions
    ports:
    - 3000:80
    links:
      - mysql
    depends_on:
      - mysql
