# pgAdmin: http://localhost:8000/
version: '3.7'
services:
  postgres:
# https://hub.docker.com/_/postgres/tags
    image: postgres:latest
#    image: postgres:15.1
#    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - ./docker/postgres/init.d:/docker-entrypoint-initdb.d
      - ./docker/postgres/pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
#    hostname: postgres
#    restart: always
    user: root
  pgadmin4:
# https://hub.docker.com/r/dpage/pgadmin4/tags
    image: dpage/pgadmin4:latest
#    image: dpage/pgadmin4:6.16
#    container_name: pgadmin4
    ports:
      - 8000:80
    volumes:
      - ./docker/pgadmin4:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: yourname@example.com
      PGADMIN_DEFAULT_PASSWORD: yourpassword
#    hostname: pgadmin4
#    restart: always
    links:
      - postgres
    depends_on:
      - postgres
